
# Arveretten


## Introduktion til arveretten

Med arvelovsrevisionen er der blevet gennemført en styrkelse af den længstlevende ægtefælles retsstilling. 

Ægtefæller vil typisk have et ønske om, at længstlevende så vidt muligt kan fortsætte sin livsførelse. 

Arveloven (AL) er derfor søgt indrettet, så dette ønske i højere grad kan realiseres, uden at ægtefællerne behøver at oprette et testamente om begrænsning af børnenes arv. 

Dette er navnlig sket ved en forhøjelse af den legale arveret, fra 1/3 til ½ af arveladerens ejendele, når arveladeren samtidig efterlader sig børn (livsarvinger).  

Arveloven indebærer endvidere, at arvelader har fået større frihed til at disponere over sin formue ved testamente. 

Livsarvingernes tvangsarv er således nedsat fra ½ til ¼ af den legale arv. Også ægtefællens tvangsarv udgør fremover ¼ af den legale arv.  

Endvidere er indført en adgang for arvelader til at begrænse en livsarvings tvangsarv til 1 mio. kr., ligesom arveladeren har fået mulighed for at bestemme, at en livsarving skal have sin tvangsarv udbetalt kontant. 

Dette indebærer, at det bl.a. bliver lettere at ligestille sammenbragte børn i arveretlig henseende, og at gennemførelsen af generationsskifter af erhvervsvirksomheder lettes.  

Herudover giver loven mulighed for, at ugifte samlevende på en særlig nem måde kan oprette testamente om gensidig arveret (et udvidet samlevertestamente). 

I sammenhæng med revisionen af arveloven er gennemført en række ændringer i forsikringsaftalelovens og pensionsopsparingslovens regler om indsættelse af begunstigede.  

De aktiver og passiver, som en afdød efterlader sig, kaldes et dødsbo. Afviklingen af dødsboet mellem arvinger og kreditorer kaldes et skifte.  

De arveretlige regler i arveloven fastlægger, hvem der er arvinger, og hvor meget og hvad den enkelte arving skal arve af det, der er i behold i boet. 

Efterlader afdøde sig ingen gæld, men alene aktiver, og ses der bort fra de forskellige regler om arveafgift (se boafgift og gaveafgift) mv., bliver det de arveretlige regler, der afgør, hvem arvebeholdningen, dvs. boets formue, skal tilfalde. 

De arveretlige regler medfører således en overgang af ejendomsretten til afdødes formue fra den afdøde til arvingerne. Arv er en erhvervelsesmåde på linje med aftale, frembringelse mv.  

En betingelse for at arve er, at arvingen har overlevet arveladeren. 

Bevis for arveladerens død vil i almindelighed let kunne føres ved fremlæggelse af en dødsattest. 

Hvis en sådan ikke kan tilvejebringes, kan en domstol undertiden statuere, at en person er død eller må anses for død (såkaldt dødsformodningsdom).  

Beviset for, at arvingen har overlevet den afdøde, kan give vanskeligheder i visse tilfælde. 

Er der ikke vished for, at en bortebleven person har overlevet afdøde, afsættes kun arv til den pågældende, hvis der er nogen sandsynlighed for, at han/hun er i live. 

Er der vished for, at arvingen har overlevet afdøde, afsættes derimod arvelod, uanset om arvingens opholdssted måtte være ukendt.  

Hvis to personer, som havde arveret efter hinanden, er døde, uden at det vides, hvem der er død først, anses den ene ikke for at have overlevet den anden. 

Reglen har praktisk betydning f.eks. ved trafikulykker, hvor ægtefæller omkommer. 

Et barn, som er avlet forinden dødsfaldet og senere fødes levende, har også arveret. Den gravide kvindes foster er således arveberettiget.  

Det siges, at "arven er faldet", når kravet på arv kan overføres ved aftale, tilegnes af arvingens kreditorer, falde i arv ved arvingens død eller indgå i arvingens eventuelle separations- eller skilsmissebo. 

Dette tidspunkt indtræder som regel ved arveladers død. 

Der gælder særregler, når arveladerens efterlevende ægtefælle overtager et fællesbo til hensidden i uskiftet bo med den førstafdødes livsarvinger.  

Arvinger kan inddeles i tre hovedgrupper: slægtninge, ægtefæller og testamentsarvinger.  

## Oversigt over arveloven

KAP. 1 SLÆGTNINGES ARVERET  
KAP. 2 ÆGTEFÆLLENS ARVERET  
KAP. 4 USKIFTET BO  
KAP. 7 AFTALE OM ARV SAMT ARVEFORSKUD  
KAP. 8 UDELUKKELSE OG BORTFALD AF ARVERET  
KAP. 9 TESTAMENTARISK BESTEMMELSE OVER TVANGSARV  
KAP. 10 TESTAMENTARISK BESTEMMELSE OVER FRIARV  
Kap. 11 OPRETTELSE OG TILBAGEKALDELSE AF TESTAMENTE  
Kap. 12 TESTAMENTES UGYLDIGHED OG ANFÆGTELSE  
 
## Arvens fordeling til arveklasser

Arven fordeles til arveklasse 1, 2 eller 3. Er der ingen arvinger i arveklasse 1 går man videre til arveklasse 2, og er der ingen arvinger i arveklasse 2, arver arveklasse 3.  

Ægtefælle har også legal arveret. Arvelader kan selv få indflydelse på fordeling af arven ved at oprette testamente. Er der ingen arvinger efter arvelov eller testamente tilfalder arven statskassen, jf. AL § 94.  

### Arveklasse 1  

Arveklasse 1 er livsarvinger, som er børn, børnebørn, oldebørn osv., jf. AL § 1. 

Børnene arver lige. 

Er et af børnene døde, træder dette barns livsarvinger i stedet og arver lige ¼ af arven er tvangsarv, jf. AL § 5. 

Børns arv kan begrænses til 1 mio. kr., jf. AL § 5, stk. 2. (1.290.000 kr. i 2019).   

AL § 1 omhandler således arv til 1. arveklasse, dvs. arveladerens livsarvinger (tvangsarvinger), som er arveladerens nærmeste slægtsarvinger. 

Børnelinjen omfatter børn, børnebørn, oldebørn osv. Slægtskab foreligger mellem en mor og hendes barn og mellem barnet og den mand, der er barnets retlige far. 

Det er en forudsætning at faderskabet er fastslået inden dødsfaldet eller efterfølgende bliver det. arver lige.  

Er et barn død, træder dets børn i dets sted og arver indbyrdes lige. På tilsvarende måde arver fjernere livsarvinger. 

Denne såkaldte stirpal-grundsætning betyder, at arven inden for hver arveklasse fordeles i »stammer« og ikke efter »hoveder«. 

Børnebørn arver således ikke, så længe barnet lever. 

Når børnebørnene arver, må de »deles« om det afdøde barns arv - det såkaldte »repræsentationsprincip«. 

På tilsvarende måde arver fjernere livsarvinger (oldebørn mv.).  

 
### Arveklasse 2  

Arveklasse 2 er arveladers forældre, jf. AL § 2. Forældrene arver lige. 

Er en af forældrene død, træder dennes børn (arveladers søskende) i stedet og arver lige. Der bliver på denne måde forskel på hel- og halvsøskende. 

Arveklasse 2 er ikke tvangsarvinger. 

Bestemmelsen i AL § 2 omhandler således arv til 2. arveklasse - forældrelinjen. 

Hvis arveladeren ikke efterlader sig livsarvinger, tilfalder arven anden arveklasse, som også kaldes udarvinger. 

Denne arveklasse udgøres af afdødes forældre og disses efterkommere, dvs. arveladerens søskende, nevøer og niecer osv. 

Lever begge arveladerens forældre, arver de hver halvdelen.  

 
### Arveklasse 3

Arveklasse 3 er arveladers bedsteforældre, jf. AL § 3. 

Arven fordeles med halvdelen til moderens forældre og halvdelen til faderens forældre. Er en af bedsteforældrene døde, træder dennes børn (arveladers faster, moster osv.) i stedet og arver lige. 

Bedsteforældre børnebørn (fætre og kusiner) arver ikke. 

Arveklasse 3 er ikke tvangsarvinger.  

Lever alle 4 bedsteforældre deles arven i 4 portioner. 

Er en af bedsteforældrene død, træder dennes børn i stedet efter repræsentationsprincippet. 

Arveladers farbrødre, fastre, mostre og morbrødre kan således være legale arvinger. Er farfaren død og efterlader sig to børn, arver disse således 1/8. 

Derimod falder arven ikke videre til fjernere livsarvinger. 

Arveladerens kusiner og fætre samt deres børn er således ikke legale arvinger.  
 
Arven mellem bedsteforældrelinien på fædrene side og bedsteforældrene på mødrene side sker efter stirpal-grundsætningen i § 2, og fordeles således ud i ¼ til hhv. farfaren eller dennes børn, farmoren eller dennes børn, mormoren eller dennes børn samt morfaren eller dennes børn. 

Er der kun arvinger på fædrene eller mødrene side, deles arven ud med ½ til hver af disse eller deres børn. 

Efterlades en mormor og to fastre, arver mormoren således ½ og fastrene ¼, mens fætre og kusiner ikke arver.  

  
--- 
 



**Video: Sådan fordeles arven**

<div class="video-container"><iframe src="https://www.youtube.com/embed/EIgZkPOF0_E" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>


---

## Længstlevendes ægtefælles arveret

Her en oversigt over længstlevendes ægtefælles arveret:  

*	Ægtefællen arver ½, hvis arvelader har børn, jf. AL § 9, stk. 1, ellers det hele jf. § 9, stk. 2. 
*	¼ af arven er tvangsarv jf. AL § 10 
*	Længstlevende ægtefælles har mulighed for at sidde i uskiftet bo
*	Suppleringsarv AL § 11, stk. 2 op til 780.000 kr. (2019) – inklusive:
  +	Boslod og særeje for længstlevende ægtefælle
  +	Arvelod for længstlevende ægtefælle
  +	Forsørgertabserstatning, livsforsikring, pension efter førstafdøde ægtefælle
  +	Ægtefællepension og ægtefælleydelse
  +	Ved længstlevende ægtefælles død, skal arven (som udgangspunkt) fordeles mellem begge ægtefællers arvinger, jf. AL § 16, stk. 2 
 
 
## Uskiftet bo for den længstlevendes ægtefælle
Vælger ægtefællen at sidde i uskiftet bo, får ægtefællen rådighed over alle aktiver og overtager afdødes gældsforpligtelser, jf. AL §§ 24 og 25. Kan kun sidde i uskiftet bo med delingsformue – særejet skal skiftes, jf. AL § 17. Man kan ikke sidde i uskiftet bo, hvis man ikke har været gift. Særbørn skal give samtykke til uskiftet bo, jf. AL § 18. Hvis længstlevende misbruger det uskiftede bos midler, kan børnene kræve skifte, jf. AL § 29.  

---

**Video: Fordeling af arv: Ægtepar med stedbørn**

https://www.youtube.com/watch?v=MQ6i9G5NxUc
<div class="video-container"><iframe src="https://www.youtube.com/embed/lXw-hdped28" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

---

Længstlevende ægtefælle kan således forbruge det uskiftede bos midler og give gaver mv., men kan af hensyn til førstafdøde ægtefælles arvinger ikke råde frit. 

Spørgsmål om misbrug kan indbringes for skifteretten af førstafdødes arvinger, jf. AL §§ 29-32. 

Længstlevende ægtefælle har rådighed uden at være egentlig ejer. 

Den pågældende kan således f.eks. stille sikkerhed, sælge aktiver hørende til det uskiftede bo og give gaver, men skal på den anden side tage hensyn til førstafdøde ægtefælles livsarvinger, idet længstlevende også råder over livsarvingernes potentielle arv efter førstafdødes ægtefælle.  

Når længstlevende dør, skal arven fordeles til begge ægtefællers livsarvinger, men der regnes ikke arv til ægtefællen, jf. AL § 28.  


## Arveladers testationskompetence

Testamenter giver arvelader mulighed for at få indflydelse på, hvem der skal arve, og hvad de skal arve.  

**Oversigt over arveladers testationskompetence**: 

Hovedreglen er, at arvelader kan ved testamente råde over hele sin formue. 

Undtagelsen er, hvis arvelader er gift og/eller har børn, er testationskompetencen begrænset af tvangsarven, jf. AL § 50  
Tvangsarven er som udgangspunkt ¼ af arveladers formue.  

**OBS: Suppleringsarv er også tvangsarv**. 

Der er tale om en tvangsarveret, der ikke kan fratages ved testamente. Retten til forlods udtagelse indebærer, at udtagelsen ikke belaster den længstlevende ægtefælles boslodskrav ved opgørelsen af fællesboet, og heller ikke kravet i henhold til retten til suppleringsarv. 

En længstlevende ægtefælles påberåbelse af AL § 11, stk. 1 vil kunne medføre, at et dødsbo kan sluttes uden skiftebehandling. 

Reglen vil derfor også i praksis blive påberåbt af en længstlevende ægtefælle, der som enearving ville kunne overtage hele boet efter AL § 9, stk. 2. 

---
 
**Video:Hvordan opretter du et testamente?**

<div class="video-container"><iframe src="https://www.youtube.com/embed/TcZb7VCClcQ" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

---

## Kravet til et gyldigt testamente  

*	at testator er fyldt 18 år (15 år for midler den umyndige selv kan råde over)
*	At testator kan handle fornuftsmæssigt
*	At testamentet opfylder kravene til:
*	Notartestamente
*	Vidnetestamente
*	Nødtestamente

### Notartestamente, jf. AL § 63

*	Notaren (i Byretten) påtegner testamentet og kontrollerer testators identitet, fornuft, mv.
*	Registrerer testamentet i Centralregistret for testamenter
*	Notartestamentet er svært at anfægte

### Vidnetestamente, jf. AL § 64

*	To vitterlighedsvidner, som ikke selv må være begunstiget i testamentet
*	Vidnerne kontrollerer testators underskrift, fornuft mv.

### Nødtestamente, jf. AL § 65

*	Kræver en nødsituation
*	Ingen formkrav
*	Bortfalder efter tre måneder

---

**Video: Fordeling af arv uden børn**

<div class="video-container"><iframe src="https://www.youtube.com/embed/bNa7tt460bY" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

**Video: Fordeling af arv med fællesbørn**

<div class="video-container"><iframe src="https://www.youtube.com/embed/TXaWe8-jz9s" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>


### Udvidet samlevertestamente

*	Samlevende har ingen legal arveret, kræver oprettelse af testamente
*	Samleverne kan arve hinanden – maksimalt 7/8 af formuen i konkurrence med børn 
*	Samleveren kan udtage suppleringsarv
*	Der kan udloddes svogerskabsarv efter længstlevende samlever
*	Samlevende kan ikke sidde i uskiftet bo
*	Udvidet samlevertestamente skal ændres ved nyt testamente
*	Udvidet samlevertestamente bortfalder ved indgåelse af ægteskab


Hvis et testamente skal ændres eller tilbagekaldes, skal ændringen overholde formkravene til testamenter, jf. AL § 67.  
Et uigenkaldeligt testamente indskrænker testators testationskompetence – arvelader har ikke mulighed for at ændre testamentet. Hvis forudsætningerne for at oprette et uigenkaldeligt testamente brister eller var urigtige, kan testamentet være ugyldigt, jf. AL § 77. 

---
  
**Video: Arv mellem sammenlevende**

<div class="video-container"><iframe src="https://www.youtube.com/embed/WVec5BYeu34" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>


---

