--- 
title: "Erhvervs- og finansjura"
author: "Sonny Kristoffersen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "JURA"
favicon: "favicon.ico"
---


#    {-}
					


<h3>***Vigtigt bem칝rk***</h3>

***Bem칝rk bogen er gratis indtil videre, s친 man skal ikke logge ind endnu***		

***Dette materiale er kun til personligt brug. Alle rettigheder forbeholdes. Fotografering, kopiering eller anden gengivelse af dette materiale, er uden forfatterens skriftlige samtykke,  forbudt, if칮lge dansk lov om ophavsret.***


***E-bogens videoer og quizer er ikke at betragte som en del af pensum, men er et supplement til pensum for at fremme din yderligere forst친else for Erhvervs- og Finansjuraen***

***Der er mulighed for selv at tilf칮je sine egne noter i e-bogen.***

***Om konstaterede fejl og mangler, samt sp칮rgsm친l til e-bogens indhold kan henvendelse ske p친 f칮lgende e-mail:***

***sk@bkhlaw.dk***

***De bedste hilsener***

***Advokat Sonny Kristoffersen, Ph.D.***



---

***Anmeldelser***

---

**E-bogen Erhvervs- og finansjura for finans칮konomer rummer rigtig mange gode ting, bl.a. de quizzer der er ved de fleste emner, det g칮r det muligt at lave et hurtigt brush up.** 
 
**Derudover er den nem at navigere i, da menuen i siden g칮r det nemt at komme til og fra de forskellige emner. Den er skrevet i et sprog som er nemt at forst친, og der er gode eksempler.** 

**Egentlig har jeg ikke s친 meget negativt at sige, den eneste ulempe er at det ikke er muligt at overstrege men s친dan er det jo generelt for E-b칮ger.**

***Emma***

---

**Jeg synes, at e-bog Erhvervs- og finansjura for finans칮konomer er sat rigtig godt op. Simpel at sl친 op, og nem og finde information i.**
 
***Nick***


---

**Jeg synes overordnet set den er super god.** 
 
**Jeg selv brugte den meget til at l칝se til eksamen. Den er overskuelig og letl칝selig, hvilket er en rigtig god ting indenfor jura, da det godt kan v칝re sv칝rt at l칝se, grundet alle de begreber man ikke kender fra hverdagen.** 
 
**Derudover synes jeg det fungere super godt, at den er s친 godt delt op i afsnit. Forst친et p친 den m친de, at tit og ofte er det noget meget konkret man s칮ger, og der er din e-bog meget brugervenlig. Det spare en for en masse tid, her t칝nker jeg ogs친 m친ske i en eksamen situation hvor man er meget presset p친 tiden**. 
 
**S친 overordnet set synes jeg den fungere vildt godt. Ydermere supplere den godt til dine powerpoint, og personligt ville jeg mene, at dine PowerPoints og din e-bog ville v칝re et rigtig godt undervisningsmateriale**. 

**Det var i hvert fald de to ting jeg st칮ttede mig op af, da jeg l칝ste til eksamen, og da jeg sad til eksamen游땕**

**Molly**

---


<br>
```{r, echo=FALSE, results='asis'}
cat(readLines('fp.html'))
```
<br>

 

---


<h3>Video s친dan k칮ber du adgang.</h3>
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/283118599' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
  <br>
  <br>

---

  <br>
  <br>
<h3>Video s친dan logger du ind.</h3>
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/283117974' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




